### ISSUE TITLE
Option for $state.go('^') to not notify the parent view

### ISSUE THREAD

**Issue by anx-ckreuzberger** [nonplus/angular-ui-router-uib-modal#5] opened 2016-04-29 08:44 UTC
Hi,

When calling `$state.go('^');` the parent view gets notified about being active again. (see https://github.com/nonplus/angular-ui-router-uib-modal/blob/master/src/angular-ui-router-uib-modal.js#L40 )

This might not be the behaviour that you want in all cases (because it could trigger reloads of REST API calls, etc...). For instance, I would like to be able to call `$state.go('^', {}, { notify: false });`.

Would it be possible to add an option for this?

Thanks!

**Comment by nonplus** [comment] 2016-04-29 15:00
Going to the parent **state** will actually not re-resolve the parent state's resolves.  So this is only a problem for code explicitly subscribing to the `$stateChange` events.

If this is really an issue for you, in the modal view, you can use `$state.go('^', {}, { notify: false })` instead of `$dismiss()`.  Alternatively, in your `$stateChange` event handler, you can compare the `fromState` and `toState` and only do the reloads when appropriate.  The second approach is probably better, since it will behave the same whether the modal is dismissed via `$dismiss()` or when the user clicks in the browser's back button.

Can you describe why your view needs to subscribe to `$stateChange` events in the first place?  I've found that my code is much cleaner when I resolve all data in the state definition and inject it into my view.

**Comment by anx-ckreuzberger** [comment] 2016-05-02 07:48
Hi,

sorry if I wasn't clear enough. My view does not need to subscribe to the `$stateChange` event. Quick outline of what I am doing (going to be use ToDo List as an example here):

I have two states: todolist and todolist.create.

State todolist: I have a list of ToDo items, which I am retrieving from a REST API (using ng resource or ng cached resource). Then I have a button to add a new ToDo item. When clicking this button, a modal dialog is opened on top of the todolist state (this is handled by using `ui-sref='todolist.create'` in the HTML code). This state has two options in the URL, which are also handled in the controller/view with some buttons:
e.g., `/#/todolist?state=FINISHED,STARTED&order_by=date`

State todolist.create: Opens a modal dialog, where the user can enter details for the new item. This is essentially a form with a save and cancel button . The user can close this modal view, by either clicking save, cancel, pressing escape or clicking outside of the view.

Everything works fine, as long as the todolist state does not have an active filter or order by. As soon as I have a filter active, and a modal dialog is opened and closed, a reload is triggered by `$state.go('^');`

I'll try to get an example up and running (though probably not today), so you can see the behaviour I am talking about.

**Comment by nonplus** [comment] 2016-05-02 15:35
Thanks, that makes more sense.  I'll look into a fix for this - I think changing the current code to something along the lines of `$state.go("^", $stateParams)` might do the trick and not reload the parent state.

**Comment by nonplus** [comment] 2016-05-05 14:55
I'm not able to reproduce your problem.  State parameters from parent state are preserved when calling `$state.go("^")` and dependencies aren't getting re-resolved.

In your example, what does the URL look like when the modal is open?  And have you declared the state parameters properly, i.e.:

```
$stateProvider
    .state("todolist", {
        url: "todolist?state,order_by",
        ...
    })
    .state("todolist.create", {
        url: "create",
        ...
    });
```

**Comment by anx-ckreuzberger** [comment] 2016-05-05 16:53
Hi,

I'll try to provide an example tomorrow or on Monday, showcasing the 
problem.

Am 05.05.2016 um 16:55 schrieb Stepan Riha:

**Comment by anx-ckreuzberger** [comment] 2016-05-06 12:20
Hi,

I have created a plnkr for this problem, containing a hopefully simple enough example:
https://plnkr.co/edit/XLEW2v7qkAeEnfyapBB1?p=preview

I included the `uib-modal-router` manually, by adding it in `ui-router/modal/orig.js`, and I have my modification in `ui-router-modal/modified.js`.

Routing is configured in `app.js`, the controllers are in the `controllers/` subfolder, partials in `partials/`.

You can see the difference in terms of what is happening by pre-viewing `index.html` (orig.js) and `index_mod.html` (modified.js).
I recommend pre-viewing in an external browser window, with the Debug Console opened, as you can see the URL changing (e.g., `?page=2`).

**Comment by nonplus** [comment] 2016-05-06 17:45
Thanks for the helpful example.  The problem is with the architecture of your application.  Specifically, you're subverting ui-router's application state management by explicitly changing states (from your pager) with `{notify:false}`.

I've forked your plunker to demonstrate how to better structure the application: https://plnkr.co/edit/x0cMLFEo52ifTQnJwoxt?p=preview

I follow the rule of thumb to resolve data (make AJAX requests) that's based on `$stateParams` in the state definition and then inject it into the controllers.  So the main changes are as follows:
- Moved access to the items into `services/items.js` (that's just to remove some of the noise from the code - your AJAX requests would be done there)
- In `app.js`, resolve the page items in the `todolist` state definition as `itemsPage` (note that I also make the `page` state parameter an integer).
- In `controllers/todolist.js`, I inject the `itemsPage` and use it to set `$state` variables.  The `pageChange` handler calls `$state.go()` **without** suppressing notification.

With these changes, state data is properly resolved at the state definition and you don't have to have `{notify: false}` in your state changes.

Note that the ToDoListController will be reloaded on `page` changes, however it won't be reloaded when going to/from the child modal state.  If this is a problem for you app, there are ways to deal with with child state definitions, but it gets a little more complex.  If you do want to keep using `{notify: false}`, in the modal controller simply use `$state.go("^", ...)` instead of `$uibModalInstance.close()/dismiss()`.

**Closed as completed** 2016-08-17 23:00 UTC
